### ISSUE TITLE
Missing data or second level

### ISSUE THREAD

**Issue by soroosh-rz** [zillow/luminaire#111]
Hi there,

I have a question rather than any specific issues. I wonder if this library can work with missing points/date during training stage? and what about anomaly detection at seconds level data? I will appreciate your response

**Comment by sayanchk** [comment]
@soroosh-rz Luminaire handles missing data based on user specifications. Luminaire DataExploration module can be used to perform smoothing-based imputation before training. Please refer to this [link](https://zillow.github.io/luminaire/tutorial/dataprofiling.htmlhttps://zillow.github.io/luminaire/tutorial/dataprofiling.html) for further details. 

Luminaire approaches anomaly detection based on the frequency of observations. Structural OR filtering modules can be used for low-frequency observation up to per hour. Luminaire has a separate [WindowDensityModel](https://zillow.github.io/luminaire/tutorial/streaming.html) which performs window-based anomaly detection which is more suitable for high-frequency data (per second, per minute, etc). This module is quite flexible though and can handle data at any frequency.

**Comment by sayanchk** [comment]
Just as a quick note, Luminaire has different profiling options for point-based outlier detection and for window-based anomaly detection. The profiling performs all necessary sanity checks (change points, trend shifts etc) for the data and applies fixes (missing data imputations, log transforms etc) to prepare the data for training. Please refer to the links above for more information.
