### ISSUE TITLE
Add getting started example

### ISSUE THREAD

**Issue by kylebuckingham** [zillow/luminaire#80]
We need a simple hello world-like example. It would also be nice to pull benchmarks from the paper out on the main page

**Comment by Aristarhys** [comment]
As option it can be ipynb? They are displayable in github directly (with some limitations)

 https://docs.github.com/en/github/managing-files-in-a-repository/working-with-jupyter-notebook-files-on-github
 
 Cell 0
 ```
 import sys
 !{sys.executable} -m pip install luminaire
 !{sys.executable} -m pip <other deps>
 ```
 
Cell 1
 ```
from luminaire.exploration.data_exploration import DataExploration
...
 ```
