### ISSUE TITLE
Enable Git LFS?

### ISSUE THREAD

**Issue by Aristarhys** [zillow/luminaire#84]
Repo have non text files in `doc/` (png, svg) and binary files in `tests/models` (probably will need to add `.bin` extensions to files there for easy tracking).

We can enable git lfs in repo settings and start tracking them

https://git-lfs.github.com/

That will allow to upload as heavy files as required in repo and without sacrifice of pull speeds.

**Comment by Aristarhys** [comment]
@snazzyfox meta, feature i guess

**Comment by snazzyfox** [comment]
Are you having trouble cloning the repo? Even though we have a couple model files checked in the entire repo is still in the low MBs range and shouldn't be a problem. You can always use the `--single-branch` option when cloning to avoid downloading unnecessary branches.
