### ISSUE TITLE
Integrate docker support

### ISSUE THREAD

**Issue by Aristarhys** [zillow/luminaire#85]
I actually have this one done - https://github.com/Aristarhys/iluminaire
But i think it's better to integrate this into main repo (if it's required), with all required changes to upgrade it to military grade dockerfile.

**Comment by Aristarhys** [comment]
@snazzyfox feature, meta i guess

**Comment by snazzyfox** [comment]
Luminaire itself is a package that can't be "run" like a service directly, so I don't really see a benefit from providing an official docker image. There are many reasons why most python packages aren't built into containers, but it boils down to the fact that any container we built can't satisfy anyone's use case unless the user builds on top of it. At that point it's easier to give user full control of their environment and just `pip install` it in the outer container.
